### ISSUE TITLE
Verified by Visa blocked

### ISSUE THREAD

**Issue by TheSchmangle** [EFForg/privacybadgerfirefox#212]
In the UK credit card payments are often authorised using Verified by Visa/Mastercard Securecode(?). Unfortunately these are being blocked by Privacy Badger and so the transaction cannot be completed until Privacy Badger is disabled. An example of a website where this occurs is https://www.national-lottery.co.uk. Instead of displaying the Verified by Visa panel there is simply a blank space. This issue does not necessarily occur on other websites.

**Comment by cooperq** [comment]
I think this is fixed by #343

**Comment by Matthew-Davey** [comment]
This is still occurring for card payments in the UK. Just had the same issue at dominos.co.uk.

Next time I see it I'll try and capture the domains which are being blocked.

**Comment by martynjarvis** [comment]
I've seen the same problem. The domain is www.securesuite.co.uk although I believe this might vary by card issuer.

I've created a PR on the chrome project here: https://github.com/EFForg/privacybadgerchrome/pull/712
