### ISSUE TITLE
Opening Privacy Badger settings results in unresponsive script error

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#643]
Windows Vista 32-bit, 1280x800 display.
Firefox 41.0.1, Privacy Badger 1.0.2
Only other add-on is BetterPrivacy 1.68.1-signed

This has been happening for a few days now:
1. I open the PB settings page
2. The page starts loading the "Filter Settings" tab. It initially shows an empty tab with just the word "Loading..."
3. This takes a long time even though I only have about 1100 trackers in the list. I didn't time it but, it is long enough for me to resent it
4. Clicking on another tab while loading leads to a brief "Not responding" state and title-bar message in Firefox then after a few senconds the switch happens
5. Anyway, eventually the list of trackers appear
6. Trying to scroll the list, move a slider or even closing or changing tabs now leads to a short delay where nothing happens then an "unresponsive script" dialog from firefox

Annoying. I used to be able to use the list and move the sliders before (when it had less items I presume).

![unresponsive-script](https://cloud.githubusercontent.com/assets/97223/10414446/3e4f076a-6fcd-11e5-94c7-0053dd10927b.png)

The line number changes in the various instances the dialog is displayed.

Hope you find this [console-output](https://cloud.githubusercontent.com/assets/97223/10414477/a78017d2-6fce-11e5-8cd8-e1ea440b8b1a.png) helpful.

**Comment by cooperq** [comment]
This is fixed as of 1.0.3 which should be out in the next couple of days.

**Comment by cypherpunk** [comment]
Can't help feeling this shouldn't have been closed until I had a chance to confirm it is indeed fixed in PB 1.0.3.

Nevertheless, thanks @cooperq, I'll look out for PB 1.0.3.

**Comment by cypherpunk** [comment]
OP here.

This issue still exists in PB 1.0.3. The dialog box often does not appear but, the unresponsiveness is still present.

The issue shouldn't have been closed until it had been confirmed fixed in PB 1.0.3.

**Comment by cooperq** [comment]
Just to confirm, this is happening when you first open the settings page correct? 
I made the process when you change one setting more efficient in 1.0.3 but the initial load is still a beast, I guess I have more work to do making that inital load less of a memory hog.

**Comment by Calefornia** [comment]
PB 1.0.5, OS X 10.10.5, Firefox 42.0.

Not sure if this is related, but my tracker list refreshes unnecessarily on the options.html page. The console performance recording shows a dramatic decrease in FPS (from 60 to 1.92) as the html is parsed and layout is calculated and rendered. This occurs even when there has been no change or addition to the local storage, all of which is in the file, store.json, I presume?

Instead, refreshing seems to be triggered by mouse events. If I click outside of the browser tab or go to another tab, the trackers are refreshed when I return to the options page. I believe the problem lies in the same jquery-1.10.2 script (or perhaps the jquery-ui.min).

I can no longer jump to the exact javascript line in my browser; Firefox says the address is invalid. When it did show code lines, I think it took me to the mouse functions. I could try playing with the source code and packaging a modified xpi with altered the mouse events in the jquery stuff. Let me know what other information might be helpful. I commented here because the refreshing might contribute to excessive rendering time and unresponsiveness.
Also, my store.json seems to have been reset somehow. I used to have over 1000 trackers, and refreshing took much longer. Now, with only around 60 trackers, the GIF doesn't reflect the delay at higher quantities. I'm trying to find an old storage file to hopefully restore the list.....

![refreshes unnecessarily](https://cloud.githubusercontent.com/assets/7418271/11646138/a4b54a40-9d0f-11e5-85d2-3981258a606c.gif)

**Comment by Calefornia** [comment]
I got my tracker list fixed and will replace that GIF with a better one, then delete this comment....
sorry for my stupidity.

**Comment by dvdbane** [comment]
still having the same issue as OP
FF 43b9 
PB 1.0.5

the page will continuously refresh even after pressing stop or continue

**Comment by cooperq** [comment]
Closed via #742
