### ISSUE TITLE
Unresponsive script on optons page

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#655]
Whenever I open the options page I get an unresponsive script.
Privacy Badger 1.0.2, Firefox 41.0.2, Mac OSX 10.9.5

![screen shot 2015-10-19 at 12 29 51 pm](https://cloud.githubusercontent.com/assets/97223/10585783/af1cdb9c-765e-11e5-94d4-6132478cf27b.jpg)

**Comment by cypherpunk** [comment]
Same issue as #643. 
Fixed in 1.0.3 according to @cooperq.

**Comment by cypherpunk** [comment]
Well, I now have 1.0.3 and I still get the unresponsive script warning.

**Comment by arthurl** [comment]
I can confirm that the issue is still around for me too, on 1.0.3.

**Comment by cooperq** [comment]
duplicate of #643 reopening that one and closing this one in favor of it.

**Comment by KidPluto** [comment]
Needs to be closed, per previous comment.  Thanks.
